### PR TITLE
Beginning of the docs

### PR DESCRIPTION
**Pull request by jMyles**
These are the docs currently on readthedocs.org.

### CODE REVIEW

**Comment by jMyles** [comment]
@vepkenez, @anthonyalmarza: What do you guys think?

**Comment by anthonyalmarza** [comment]
:+1:

**Comment by anthonyalmarza** [comment]
Wait... where's the mkdocs file?

**Comment by jMyles** [comment]
Ummm, yeah - it looks like there isn't one.  I guess readthedocs has sane
defaults?  mkdocs support is fairly new.  I don't recall whether I was
following a guide.

**Comment by vepkenez** [comment]
A great start!

**Comment by anthonyalmarza** [comment]
Yeah mkdocs is pretty cool. I had a go at following the docs on a different repo but it didn't quite work. I found that having the mkdocs file on the same level as setup.py and the md files in a docs folder worked well for me. But yeah, I think that you're right about the rtd default settings.

**Comment by jMyles** [comment]
So, are you ready to merge?  If so, please do so and then let me give you a
tour of the next merge: crosstown_traffic.

**Pull request merged**
