### PR TITLE
0.9.0 Release Candidate

### PR DESCRIPTION
**Pull request by jMyles**
Code reorg is materially complete, although there are still a few "reasonable people might disagree" namespacing decisions to be made or decided not to be made.

At this point, the APIs are set to my satisfaction and they match the organization structure laid out in #80.

### CODE REVIEW

**Comment by jMyles** [comment]
Any thoughts on this Pull Request?  Any stray ImportErrors from the refactors?

**Comment by shaane** [comment]
Already using this request for a project. Seems to be working just fine. :+1:

**Comment by ckaye89** [comment]
Excited to be using this for our blog: https://upsidedownhomewardbound.us/. :-)

**Comment by KPrasch** [comment]
I'd like to see this pull request accepted.  I'm using this release candidate in multiple production environments, and am planning on deploying it in two more, all of which will utilize the crosstown_traffic API.  

This pull request is going on it's third pending week.  At ~25 commits ahead, and full of just awesome code, I'm willing to do whatever it takes to have commit #88 declared as version 0.9, get this pull request accepted, and have the new version officially installable via python-pip.

I can imagine there is a code review or some other due process that needs to occur here but I'm ready *today* to manage the merge.

What can I do to push this along? Can we have an official statement if there some blocking issue?

Thanks ahead of time.

**Comment by vepkenez** [comment]
Still need to update the pip

**Pull request merged**
